### ISSUE TITLE
Extension can't login

### ISSUE THREAD

**Issue by chross** [BenjaminHae/PwChromeExtension#39]
Hi,
I'm on Firefox 53.0.2 and using Password Manager 9.15. When using the extension on a website I have an entry for, I am always presented with the login screen that will automatically login followed by a message **Login failed, due to missing secretkey**

Is this a problem with the extension or the pwdmgr?

**Comment by BenjaminHae** [comment]
Hi,
thank you for reporting this.
If I remember correctly it's something I've fixed in the version that's available in the chrome webstore.
Sadly I forgot to upload the new release for firefox.
I'll probably have time to create the new release this weekend. If you want to you could try on chrome if it works?

**Comment by BenjaminHae** [comment]
I just uploaded the 0.3.2 release for firefox. Could you please verify it's working?
Thanks!

**Comment by BenjaminHae** [comment]
No answer in 5 months and probably solved.
